.TH "MATE-NOTIFICATION-PROPERTIES" "1" "15 Jan, 2014" "" ""

.SH NAME
mate\-notification\-properties \- MATE notification properties gui
.SH SYNOPSIS

\fBmate\-notification\-properties\fR

.SH "DESCRIPTION"
.PP
This manual page briefly documents the
\fBmate\-notification\-properties\fR command.
.PP
\fBmate\-notification\-properties\fR is a GUI programme for tweaking the properties of the MATE
notification daemon.
.SH "SEE ALSO"
.PP
The program is fully documented at
http://mate.org/projects/mate\-notification\-daemon/ .
.SH "AUTHOR"
.PP
This manual page was written by Mike Gabriel <sunweaver@debian.org> for
the Debian project and may be used by others.
